GET http://localhost:3000

### Create a new user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "user_name": "Jane Smith",
  "user_email": "janesmith@example.com",
  "user_password": "password456",
  "role_id": 1
}

### Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "user_email": "janesmith@example.com",
  "user_password": "password456"
}
    
### Create new shop item
POST http://localhost:3000/api/shop_items
Content-Type: application/json

{
  "shop_item_name": "Example Item",
  "shop_item_price": 19.99,
  "shop_item_description": "This is an example item",
  "shop_item_image": "example.jpg",
  "item_type_id": 1
}

### Get all shop items
GET http://localhost:3000/api/shop_items


### Get shop item by id
GET http://localhost:3000/api/shop_items/3

